version: '3.9'

services:
 mysqldb:
  image: mysql
  ports:
  - 3310:3306
  environment:
  - MYSQL_DATABASE=apiRestTest
  - MYSQL_ROOT_PASSWORD=1234
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: